### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by victimizing** [kinsoRick/twitch-drops#1]
i left the script on overnight and this is what i came back to; https://prnt.sc/yd0roo

https://prnt.sc/yd0k76 the bug is, the bot is relying on user panel to get drop information, and the panel is slow by a few mins and thinks im watching over streamers, and shows the stats for those streamers rather than the one im watching!

due to this bug, i get 100% on one streamer, it thinks all streamers are 100% and skips them, and i only get half way through

another bug is the bot continues to watch a streamer already completed and stays stuck on 0% because it can't find a percentage for how much is completed of the streamer due to it already being completed

another bug, **?referrer=raid** when people are referred  / raided to by another streamer, the bot doesn't check for this, and continues watching, progressing nothing on the twitch drops!

another bug, https://prnt.sc/yd1uh8, i dont know where its getting the "1%" from but itll probably make the bot stay watching the streamer for longer than normal xd

also, a suggestion, use https://twitch.facepunch.com/ to get streamer online stats, its better than sending a lot of reqs going to all streamers individually (and i think facepunch only displays online if they have drops enabled too, even better)

**Comment by kinsoRick** [comment]
Thank you!
Your suggestion to get a list of streamers through the site is interesting, but the script is not only for Rust.
I have fixed several bugs.

**Comment by victimizing** [comment]
thank you for making this script brother its very handy!
downloading new version now
